spring:
  # Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:../data/templateDB;AUTO_SERVER=TRUE
    username: postgres
    password: Gega123_
  # Acceso a la consola de H2
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
