spring:
  # SQL
  sql:
    init:
      mode: always
  # Database
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:E:/Projects/Personal Project/CV Projects/Template-Microservicies/data/templateDB.mv.db;AUTO_SERVER=TRUE'
    username: admin
    password: Gega123_
  # Acceso a la consola de H2
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
